name: set secret v2

on:
  workflow_dispatch:
    inputs:
      vkey:
        type: string
        description: 'key'
        required: true
      vval:
        type: string
        description: 'value'
        required: true
        

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PID3 }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name : ss1
        run: supabase secrets set --project-ref ${{ secrets.SUPABASE_PID3 }} ${{ inputs.vkey}}=${{ inputs.vval}}


