# This is a basic workflow that is manually triggered

name: telehook
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  repository_dispatch:
    types:
      - telehooks
      
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: actions/checkout@v3
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
      with:
          java-version: 8
    - run: |
        mkdir out
        ls -Rlh
    - name: compile telegram message handler
      run: javac Botm.java
    - run: ls -Rlth
    - name: reply
      run: java Botm "${{secrets.btc}}" "${{github.event.client_payload.chatid}}" "${{github.event.client_payload.text}}"
    - name: lsd
      run: ls -Rlth
